### ISSUE TITLE
Unable to find a device matching the device query error

### ISSUE THREAD

**Issue by moatazeldebsy** [saucelabs-training/demo-xcuitest#6]
Hi, I'm trying to run the XCUITest using saucectl but I', getting this error `Unable to find a device matching the device query`

I have a config file with the following configuration

```
apiVersion: v1alpha
kind: xcuitest
sauce:
  region: eu-central-1
  concurrency: 1
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release

xcuitest:
  app: ./Debug-iphonesimulator/FoodTruck.app
  testApp: ./Debug-iphonesimulator/FoodTruckUITests-Runner.app

suites:
  - name: "Run all tests"
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone Simulator"
        platformVersion: "16.0"

artifacts:
  download:
    when: always
    match:
      - "junit.xml"
    directory: ./artifacts/
```

But every time it gives me this error and also on SauceLabs the results are under the real devices not virtual. 

<img width="920" alt="Screenshot 2022-11-14 at 16 42 34" src="https://user-images.githubusercontent.com/45570191/201702832-4f55d77f-0392-49c2-9d2b-c6cbf2915cfe.png">

<img width="801" alt="Screenshot 2022-11-14 at 16 42 42" src="https://user-images.githubusercontent.com/45570191/201702843-ca22f97c-9193-41f6-9725-340fd9b6a182.png">

and run the tests using: 

`saucectl run -c config.yml
`
So what's wrong with this configuration?

Thanks
